export const ErrorCodes = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  INVALID_CODE: 'INVALID_CODE',
  EXPIRED_CODE: 'EXPIRED_CODE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  NOT_VERIFIED: 'NOT_VERIFIED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SMTP_NOT_CONFIGURED: 'SMTP_NOT_CONFIGURED',
  SMTP_BAD_PORT: 'SMTP_BAD_PORT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
